function bdd() {
  const donneesMeteoLyon = {
    janvier2009: {
      date: "janvier 2009",
      temperatureMax: "4°C",
      temperatureMin: "-2°C",
      humidite: "88%",
    },
    fevrier2009: {
      date: "février 2009",
      temperatureMax: "6°C",
      temperatureMin: "0°C",
      humidite: "93%",
    },
    mars2009: {
      date: "mars 2009",
      temperatureMax: "10°C",
      temperatureMin: "2°C",
      humidite: "91%",
    },
    avril2009: {
      date: "avril 2009",
      temperatureMax: "16°C",
      temperatureMin: "8°C",
      humidite: "93%",
    },
    mai2009: {
      date: "mai 2009",
      temperatureMax: "22°C",
      temperatureMin: "13°C",
      humidite: "84%",
    },
    juin2009: {
      date: "juin 2009",
      temperatureMax: "23°C",
      temperatureMin: "15°C",
      humidite: "88%",
    },
    juillet2009: {
      date: "juillet 2009",
      temperatureMax: "26°C",
      temperatureMin: "17°C",
      humidite: "85%",
    },
    aout2009: {
      date: "août 2009",
      temperatureMax: "28°C",
      temperatureMin: "17°C",
      humidite: "84%",
    },
    septembre2009: {
      date: "septembre 2009",
      temperatureMax: "22°C",
      temperatureMin: "12°C",
      humidite: "93%",
    },
    octobre2009: {
      date: "octobre 2009",
      temperatureMax: "16°C",
      temperatureMin: "7°C",
      humidite: "90%",
    },
    novembre2009: {
      date: "novembre 2009",
      temperatureMax: "12°C",
      temperatureMin: "7°C",
      humidite: "89%",
    },
    decembre2009: {
      date: "décembre 2009",
      temperatureMax: "6°C",
      temperatureMin: "1°C",
      humidite: "91%",
    },
    janvier2010: {
      date: "janvier 2010",
      temperatureMax: "2°C",
      temperatureMin: "-2°C",
      humidite: "94%",
    },
    mars2010: {
      date: "mars 2010",
      temperatureMax: "10°C",
      temperatureMin: "2°C",
      humidite: "89%",
    },
    fevrier2010: {
      date: "février 2010",
      temperatureMax: "6°C",
      temperatureMin: "0°C",
      humidite: "93%",
    },
    avril2010: {
      date: "avril 2010",
      temperatureMax: "16°C",
      temperatureMin: "7°C",
      humidite: "90%",
    },
    mai2010: {
      date: "mai 2010",
      temperatureMax: "16°C",
      temperatureMin: "9°C",
      humidite: "92%",
    },
    juin2010: {
      date: "juin 2010",
      temperatureMax: "22°C",
      temperatureMin: "15°C",
      humidite: "92%",
    },
    juillet2010: {
      date: "juillet 2010",
      temperatureMax: "27°C",
      temperatureMin: "18°C",
      humidite: "85%",
    },
    aout2010: {
      date: "août 2010",
      temperatureMax: "24°C",
      temperatureMin: "15°C",
      humidite: "89%",
    },
    septembre2010: {
      date: "septembre 2010",
      temperatureMax: "20°C",
      temperatureMin: "10°C",
      humidite: "93%",
    },
    octobre2010: {
      date: "octobre 2010",
      temperatureMax: "15°C",
      temperatureMin: "6°C",
      humidite: "94%",
    },
    novembre2010: {
      date: "novembre 2010",
      temperatureMax: "9°C",
      temperatureMin: "4°C",
      humidite: "96%",
    },
    decembre2010: {
      date: "décembre 2010",
      temperatureMax: "3°C",
      temperatureMin: "-2°C",
      humidite: "96%",
    },
    janvier2011: {
      date: "janvier 2011",
      temperatureMax: "3°C",
      temperatureMin: "-1°C",
      humidite: "93%",
    },
    fevrier2011: {
      date: "février 2011",
      temperatureMax: "5°C",
      temperatureMin: "0°C",
      humidite: "89%",
    },
    mars2011: {
      date: "mars 2011",
      temperatureMax: "8°C",
      temperatureMin: "3°C",
      humidite: "93%",
    },
    avril2011: {
      date: "avril 2011",
      temperatureMax: "14°C",
      temperatureMin: "9°C",
      humidite: "89%",
    },
    mai2011: {
      date: "mai 2011",
      temperatureMax: "17°C",
      temperatureMin: "13°C",
      humidite: "90%",
    },
    juin2011: {
      date: "juin 2011",
      temperatureMax: "18°C",
      temperatureMin: "14°C",
      humidite: "93%",
    },
    juillet2011: {
      date: "juillet 2011",
      temperatureMax: "18°C",
      temperatureMin: "15°C",
      humidite: "93%",
    },
    aout2011: {
      date: "août 2011",
      temperatureMax: "21°C",
      temperatureMin: "16°C",
      humidite: "90%",
    },
    septembre2011: {
      date: "septembre 2011",
      temperatureMax: "18°C",
      temperatureMin: "13°C",
      humidite: "95%",
    },
    octobre2011: {
      date: "octobre 2011",
      temperatureMax: "12°C",
      temperatureMin: "8°C",
      humidite: "94%",
    },
    novembre2011: {
      date: "novembre 2011",
      temperatureMax: "9°C",
      temperatureMin: "5°C",
      humidite: "89%",
    },
    decembre2011: {
      date: "décembre 2011",
      temperatureMax: "5°C",
      temperatureMin: "3°C",
      humidite: "93%",
    },
    janvier2012: {
      date: "janvier 2012",
      temperatureMax: "6°C",
      temperatureMin: "1°C",
      humidite: "91%",
    },
    février2012: {
      date: "février 2012",
      temperatureMax: "2°C",
      temperatureMin: "-6°C",
      humidite: "92%",
    },
    mars2012: {
      date: "mars 2012",
      temperatureMax: "15°C",
      temperatureMin: "3°C",
      humidite: "93%",
    },
    avril2012: {
      date: "avril 2012",
      temperatureMax: "13°C",
      temperatureMin: "6°C",
      humidite: "93%",
    },
    mai2012: {
      date: "mai 2012",
      temperatureMax: "19°C",
      temperatureMin: "12°C",
      humidite: "93%",
    },
    juin2012: {
      date: "juin 2012",
      temperatureMax: "23°C",
      temperatureMin: "15°C",
      humidite: "94%",
    },
    juillet2012: {
      date: "juillet 2012",
      temperatureMax: "23°C",
      temperatureMin: "16°C",
      humidite: "92%",
    },
    août2012: {
      date: "août 2012",
      temperatureMax: "26°C",
      temperatureMin: "17°C",
      humidite: "92%",
    },
    septembre2012: {
      date: "septembre 2012",
      temperatureMax: "21°C",
      temperatureMin: "11°C",
      humidite: "94%",
    },
    octobre2012: {
      date: "octobre 2012",
      temperatureMax: "17°C",
      temperatureMin: "8°C",
      humidite: "91%",
    },
    novembre2012: {
      date: "novembre 2012",
      temperatureMax: "11°C",
      temperatureMin: "4°C",
      humidite: "92%",
    },
    décembre2012: {
      date: "décembre 2012",
      temperatureMax: "7°C",
      temperatureMin: "2°C",
      humidite: "93%",
    },
    janvier2013: {
      date: "janvier 2013",
      temperatureMax: "5°C",
      temperatureMin: "0°C",
      humidite: "90%",
    },
    février2013: {
      date: "février 2013",
      temperatureMax: "4°C",
      temperatureMin: "-2°C",
      humidite: "91%",
    },
    mars2013: {
      date: "mars 2013",
      temperatureMax: "10°C",
      temperatureMin: "1°C",
      humidite: "89%",
    },
    avril2013: {
      date: "avril 2013",
      temperatureMax: "15°C",
      temperatureMin: "6°C",
      humidite: "87%",
    },
    mai2013: {
      date: "mai 2013",
      temperatureMax: "15°C",
      temperatureMin: "9°C",
      humidite: "86%",
    },
    juin2013: {
      date: "juin 2013",
      temperatureMax: "21°C",
      temperatureMin: "14°C",
      humidite: "85%",
    },
    juillet2013: {
      date: "juillet 2013",
      temperatureMax: "27°C",
      temperatureMin: "18°C",
      humidite: "88%",
    },
    août2013: {
      date: "août 2013",
      temperatureMax: "25°C",
      temperatureMin: "15°C",
      humidite: "89%",
    },
    septembre2013: {
      date: "septembre 2013",
      temperatureMax: "21°C",
      temperatureMin: "12°C",
      humidite: "85%",
    },
    octobre2013: {
      date: "octobre 2013",
      temperatureMax: "18°C",
      temperatureMin: "10°C",
      humidite: "88%",
    },
    novembre2013: {
      date: "novembre 2013",
      temperatureMax: "8°C",
      temperatureMin: "3°C",
      humidite: "89%",
    },
    décembre2013: {
      date: "décembre 2013",
      temperatureMax: "8°C",
      temperatureMin: "1°C",
      humidite: "90%",
    },
    janvier2014: {
      date: "janvier 2014",
      temperatureMax: "8°C",
      temperatureMin: "3°C",
      humidite: "93%",
    },
    février2014: {
      date: "février 2014",
      temperatureMax: "9°C",
      temperatureMin: "2°C",
      humidite: "92%",
    },
    mars2014: {
      date: "mars 2014",
      temperatureMax: "14°C",
      temperatureMin: "3°C",
      humidite: "91%",
    },
    avril2014: {
      date: "avril 2014",
      temperatureMax: "17°C",
      temperatureMin: "8°C",
      humidite: "90%",
    },
    mai2014: {
      date: "mai 2014",
      temperatureMax: "18°C",
      temperatureMin: "10°C",
      humidite: "91%",
    },
    juin2014: {
      date: "juin 2014",
      temperatureMax: "24°C",
      temperatureMin: "15°C",
      humidite: "88%",
    },
    juillet2014: {
      date: "juillet 2014",
      temperatureMax: "23°C",
      temperatureMin: "16°C",
      humidite: "92%",
    },
    août2014: {
      date: "août 2014",
      temperatureMax: "23°C",
      temperatureMin: "14°C",
      humidite: "92%",
    },
    septembre2014: {
      date: "septembre 2014",
      temperatureMax: "22°C",
      temperatureMin: "12°C",
      humidite: "94%",
    },
    octobre2014: {
      date: "octobre 2014",
      temperatureMax: "19°C",
      temperatureMin: "10°C",
      humidite: "94%",
    },
    novembre2014: {
      date: "novembre 2014",
      temperatureMax: "13°C",
      temperatureMin: "6°C",
      humidite: "91%",
    },
    décembre2014: {
      date: "décembre 2014",
      temperatureMax: "6°C",
      temperatureMin: "2°C",
      humidite: "92%",
    },
    janvier2015: {
      date: "janvier 2015",
      temperatureMax: "6°C",
      temperatureMin: "0°C",
      humidite: "91%",
    },
    février2015: {
      date: "février 2015",
      temperatureMax: "5°C",
      temperatureMin: "-1°C",
      humidite: "90%",
    },
    mars2015: {
      date: "mars 2015",
      temperatureMax: "11°C",
      temperatureMin: "4°C",
      humidite: "90%",
    },
    avril2015: {
      date: "avril 2015",
      temperatureMax: "16°C",
      temperatureMin: "7°C",
      humidite: "83%",
    },
    mai2015: {
      date: "mai 2015",
      temperatureMax: "20°C",
      temperatureMin: "12°C",
      humidite: "84%",
    },
    juin2015: {
      date: "juin 2015",
      temperatureMax: "25°C",
      temperatureMin: "17°C",
      humidite: "82%",
    },
    juillet2015: {
      date: "juillet 2015",
      temperatureMax: "29°C",
      temperatureMin: "20°C",
      humidite: "75%",
    },
    août2015: {
      date: "août 2015",
      temperatureMax: "27°C",
      temperatureMin: "17°C",
      humidite: "79%",
    },
    septembre2015: {
      date: "septembre 2015",
      temperatureMax: "20°C",
      temperatureMin: "11°C",
      humidite: "89%",
    },
    octobre2015: {
      date: "octobre 2015",
      temperatureMax: "15°C",
      temperatureMin: "6°C",
      humidite: "92%",
    },
    novembre2015: {
      date: "novembre 2015",
      temperatureMax: "13°C",
      temperatureMin: "5°C",
      humidite: "89%",
    },
    décembre2015: {
      date: "décembre 2015",
      temperatureMax: "11°C",
      temperatureMin: "4°C",
      humidite: "91%",
    },
    janvier2016: {
      date: "janvier 2016",
      temperatureMax: "8°C",
      temperatureMin: "2°C",
      humidite: "90%",
    },
    février2016: {
      date: "février 2016",
      temperatureMax: "9°C",
      temperatureMin: "3°C",
      humidite: "90%",
    },
    mars2016: {
      date: "mars 2016",
      temperatureMax: "11°C",
      temperatureMin: "2°C",
      humidite: "91%",
    },
    avril2016: {
      date: "avril 2016",
      temperatureMax: "14°C",
      temperatureMin: "7°C",
      humidite: "87%",
    },
    mai2016: {
      date: "mai 2016",
      temperatureMax: "17°C",
      temperatureMin: "11°C",
      humidite: "87%",
    },
    juin2016: {
      date: "juin 2016",
      temperatureMax: "21°C",
      temperatureMin: "15°C",
      humidite: "91%",
    },
    juillet2016: {
      date: "juillet 2016",
      temperatureMax: "24°C",
      temperatureMin: "17°C",
      humidite: "87%",
    },
    août2016: {
      date: "août 2016",
      temperatureMax: "26°C",
      temperatureMin: "16°C",
      humidite: "83%",
    },
    septembre2016: {
      date: "septembre 2016",
      temperatureMax: "24°C",
      temperatureMin: "13°C",
      humidite: "88%",
    },
    octobre2016: {
      date: "octobre 2016",
      temperatureMax: "15°C",
      temperatureMin: "5°C",
      humidite: "94%",
    },
    novembre2016: {
      date: "novembre 2016",
      temperatureMax: "10°C",
      temperatureMin: "4°C",
      humidite: "92%",
    },
    décembre2016: {
      date: "décembre 2016",
      temperatureMax: "8°C",
      temperatureMin: "0°C",
      humidite: "85%",
    },
    janvier2017: {
      date: "janvier 2017",
      temperatureMax: "3°C",
      temperatureMin: "-4°C",
      humidite: "89%",
    },
    février2017: {
      date: "février 2017",
      temperatureMax: "10°C",
      temperatureMin: "3°C",
      humidite: "91%",
    },
    mars2017: {
      date: "mars 2017",
      temperatureMax: "14°C",
      temperatureMin: "5°C",
      humidite: "92%",
    },
    avril2017: {
      date: "avril 2017",
      temperatureMax: "15°C",
      temperatureMin: "6°C",
      humidite: "90%",
    },
    mai2017: {
      date: "mai 2017",
      temperatureMax: "20°C",
      temperatureMin: "13°C",
      humidite: "88%",
    },
    juin2017: {
      date: "juin 2017",
      temperatureMax: "25°C",
      temperatureMin: "18°C",
      humidite: "85%",
    },
    juillet2017: {
      date: "juillet 2017",
      temperatureMax: "27°C",
      temperatureMin: "18°C",
      humidite: "84%",
    },
    août2017: {
      date: "août 2017",
      temperatureMax: "28°C",
      temperatureMin: "17°C",
      humidite: "83%",
    },
    septembre2017: {
      date: "septembre 2017",
      temperatureMax: "20°C",
      temperatureMin: "10°C",
      humidite: "90%",
    },
    octobre2017: {
      date: "octobre 2017",
      temperatureMax: "19°C",
      temperatureMin: "9°C",
      humidite: "87%",
    },
    novembre2017: {
      date: "novembre 2017",
      temperatureMax: "10°C",
      temperatureMin: "3°C",
      humidite: "89%",
    },
    décembre2017: {
      date: "décembre 2017",
      temperatureMax: "6°C",
      temperatureMin: "1°C",
      humidite: "93%",
    },
    janvier2018: {
      date: "janvier 2018",
      temperatureMax: "10°C",
      temperatureMin: "4°C",
      humidite: "92%",
    },
    février2018: {
      date: "février 2018",
      temperatureMax: "5°C",
      temperatureMin: "-1°C",
      humidite: "87%",
    },
    mars2018: {
      date: "mars 2018",
      temperatureMax: "11°C",
      temperatureMin: "3°C",
      humidite: "92%",
    },
    avril2018: {
      date: "avril 2018",
      temperatureMax: "19°C",
      temperatureMin: "9°C",
      humidite: "86%",
    },
    mai2018: {
      date: "mai 2018",
      temperatureMax: "21°C",
      temperatureMin: "13°C",
      humidite: "91%",
    },
    juin2018: {
      date: "juin 2018",
      temperatureMax: "25°C",
      temperatureMin: "16°C",
      humidite: "88%",
    },
    juillet2018: {
      date: "juillet 2018",
      temperatureMax: "30°C",
      temperatureMin: "19°C",
      humidite: "80%",
    },
    août2018: {
      date: "août 2018",
      temperatureMax: "28°C",
      temperatureMin: "17°C",
      humidite: "84%",
    },
    septembre2018: {
      date: "septembre 2018",
      temperatureMax: "25°C",
      temperatureMin: "13°C",
      humidite: "85%",
    },
    octobre2018: {
      date: "octobre 2018",
      temperatureMax: "18°C",
      temperatureMin: "9°C",
      humidite: "91%",
    },
    novembre2018: {
      date: "novembre 2018",
      temperatureMax: "12°C",
      temperatureMin: "5°C",
      humidite: "91%",
    },
    décembre2018: {
      date: "décembre 2018",
      temperatureMax: "9°C",
      temperatureMin: "3°C",
      humidite: "90%",
    },
    janvier2019: {
      date: "janvier 2019",
      temperatureMax: "5°C",
      temperatureMin: "-1°C",
      humidite: "92%",
    },
    février2019: {
      date: "février 2019",
      temperatureMax: "12°C",
      temperatureMin: "2°C",
      humidite: "85%",
    },
    mars2019: {
      date: "mars 2019",
      temperatureMax: "13°C",
      temperatureMin: "4°C",
      humidite: "87%",
    },
    avril2019: {
      date: "avril 2019",
      temperatureMax: "15°C",
      temperatureMin: "6°C",
      humidite: "88%",
    },
    mai2019: {
      date: "mai 2019",
      temperatureMax: "17°C",
      temperatureMin: "9°C",
      humidite: "88%",
    },
    juin2019: {
      date: "juin 2019",
      temperatureMax: "26°C",
      temperatureMin: "17°C",
      humidite: "83%",
    },
    juillet2019: {
      date: "juillet 2019",
      temperatureMax: "28°C",
      temperatureMin: "19°C",
      humidite: "83%",
    },
    août2019: {
      date: "août 2019",
      temperatureMax: "27°C",
      temperatureMin: "17°C",
      humidite: "85%",
    },
    septembre2019: {
      date: "septembre 2019",
      temperatureMax: "23°C",
      temperatureMin: "12°C",
      humidite: "87%",
    },
    octobre2019: {
      date: "octobre 2019",
      temperatureMax: "18°C",
      temperatureMin: "11°C",
      humidite: "91%",
    },
    novembre2019: {
      date: "novembre 2019",
      temperatureMax: "9°C",
      temperatureMin: "5°C",
      humidite: "94%",
    },
    décembre2019: {
      date: "décembre 2019",
      temperatureMax: "9°C",
      temperatureMin: "4°C",
      humidite: "89%",
    },
  };
  return donneesMeteoLyon;
}

export default bdd;
